[package]
name = "mir_opt"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false

[dependencies]
stdx = { version = "0.0.0", path = "../../lib/stdx" }
workqueue = { version = "0.0.0", path = "../../lib/workqueue" }
bitset = { version = "0.0.0", path = "../../lib/bitset" }

mir = { version = "0.0.0", path = "../mir" }

ahash = "0.8"
hashbrown = { version = "0.14", features = ["raw"] }
typed-index-collections = "3"

[dev-dependencies]
mir_reader = { version = "0.0.0", path = "../mir_reader" }

expect-test = "1.4"
