//! Target Information

use std::ffi::CString;
use std::mem::MaybeUninit;

use libc::{c_char, c_uint, c_ulonglong};

use crate::support::LLVMString;
use crate::{
    Bool, CodeGenFileType, CodeModel, LLVMSetTarget, Module, OptLevel, RelocMode, Target,
    TargetData, TargetMachine, Type,
};

extern "C" {
    /// Creates target data from a target layout string.
    pub fn LLVMCreateTargetData(StringRep: *const c_char) -> &'static mut TargetData;
    /// Deallocates a TargetData.
    pub fn LLVMDisposeTargetData(target_data: &'static mut TargetData);
    /// Computes the ABI size of a type in bytes for a target.
    pub fn LLVMABISizeOfType(data: &TargetData, ty: &Type) -> c_ulonglong;
    /// Computes the ABI alignment of a type in bytes for a target.
    pub fn LLVMABIAlignmentOfType(data: &TargetData, ty: &Type) -> c_uint;
    /// Computes the byte offset of the indexed struct element for a target.
    pub fn LLVMOffsetOfElement(data: &TargetData, struct_ty: &Type, elem: c_uint) -> c_ulonglong;
    /// Finds the target corresponding to the given triple and stores it in T.
    /// Returns 0 on success. Optionally returns any error in ErrorMessage.
    /// Use LLVMDisposeMessage to dispose the message.
    fn LLVMGetTargetFromTriple(
        triple: *const c_char,
        target: &mut Option<&'static Target>,
        err_msg: *mut *mut c_char,
    ) -> Bool;
    /// Creates a new llvm::TargetMachine.
    fn LLVMCreateTargetMachine(
        target: &Target,
        triple: *const c_char,
        cpu: *const c_char,
        features: *const c_char,
        level: OptLevel,
        reloc_mode: RelocMode,
        code_model: CodeModel,
    ) -> Option<&'static mut TargetMachine>;
    /// Dispose the LLVMTargetMachineRef instance generated by LLVMCreateTargetMachine.
    pub fn LLVMDisposeTargetMachine(target_machine: &'static mut TargetMachine);
    /// Emits an asm or object file for the given module to the filename.
    pub fn LLVMTargetMachineEmitToFile(
        target: &TargetMachine,
        module: &Module,
        file_name: *const c_char,
        codegen: CodeGenFileType,
        err_msg: *mut *mut c_char,
    ) -> Bool;
    // /// Compile the LLVM IR stored in M and store the result in OutMemBuf.
    // pub fn LLVMTargetMachineEmitToMemoryBuffer(
    //     T: LLVMTargetMachineRef,
    //     M: LLVMModuleRef,
    //     codegen: LLVMCodeGenFileType,
    //     ErrorMessage: *mut *mut ::libc::c_char,
    //     OutMemBuf: *mut LLVMMemoryBufferRef,
    // ) -> LLVMBool;
    /// Normalize a target triple.
    /// The result needs to be disposed with LLVMDisposeMessage.
    fn LLVMNormalizeTargetTriple(triple: *const c_char) -> *mut c_char;
    pub fn LLVMGetHostCPUName() -> *const c_char;
    pub fn LLVMGetHostCPUFeatures() -> *const c_char;
}

/// # Safety
/// This function calls the LLVM C API and may cause unsafety for invalid inputs.
///
/// Specifically, this function is not thread safe!
pub unsafe fn create_target_machine(
    module: &Module,
    triple: &str,
    cpu: &str,
    features: &str,
    opt_level: OptLevel,
    reloc_mode: RelocMode,
    code_model: CodeModel,
) -> Result<&'static mut TargetMachine, LLVMString> {
    let triple_ = LLVMString::from_str(triple);
    let triple_ = LLVMString::new(LLVMNormalizeTargetTriple(triple_.as_ptr()));
    LLVMSetTarget(module, triple_.as_ptr());

    let mut target = None;
    let mut err_string = MaybeUninit::uninit();
    if LLVMGetTargetFromTriple(triple_.as_ptr(), &mut target, err_string.as_mut_ptr()) == 1 {
        return Err(LLVMString::new(err_string.assume_init()));
    }
    let cpu = LLVMString::from_str(cpu);
    let features = CString::new(features).unwrap();

    let target_machine = LLVMCreateTargetMachine(
        target.unwrap(),
        triple_.as_ptr(),
        cpu.as_ptr(),
        features.as_ptr(),
        opt_level,
        reloc_mode,
        code_model,
    );

    target_machine.ok_or_else(|| {
        let msg = format!("error: codegen not available for target \"{triple}\"");
        LLVMString::from_str(&msg)
    })
}
