[package]
name = "basedb"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[badges]
maintenance = { status = "actively-developed" }

[lib]
doctest = false

[dependencies]
stdx = { version = "0.0.0", path = "../../lib/stdx" }
arena = { version = "0.0.0", path = "../../lib/arena" }
typed_indexmap = { version = "0.0.0", path = "../../lib/typed_indexmap" }
vfs = { version = "0.0.0", path = "../vfs" }
syntax = { version = "0.0.0", path = "../syntax" }

salsa = "0.17.0-pre.2"
codespan-reporting = { version = "0.12" }
parking_lot = "0.12"
ahash = "0.8"
typed-index-collections = "3"

[dev-dependencies]
expect-test = "1.4"
mini_harness = { version = "0.0.1", path = "../../lib/mini_harness" }

[[test]]
name = "data_tests"
harness = false
