[package]
name = "preprocessor"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false

[dependencies]
stdx = { version = "0.0.0", path = "../../lib/stdx" }
vfs = { version = "0.0.0", path = "../vfs" }
tokens = { version = "0.0.0", path = "../tokens" }
lexer = { version = "0.0.0", path = "../lexer" }

ahash = "0.8"
typed-index-collections = "3"

[dev-dependencies]
expect-test = "1.4.1"
