[package]
name = "osdi"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false

[dependencies]

stdx = { version = "0.0.0", path = "../../lib/stdx" }
paths = {version = "0.0", path = "../../lib/paths"}
base_n = {version = "1", path="../../lib/base_n"}
typed_indexmap = {version = "0.0.0", path = "../../lib/typed_indexmap"}

hir = { version = "0.0.0", path = "../hir" }
mir = { version = "0.0.0", path = "../mir" }
hir_lower = {version ="0.0.0", path ="../hir_lower"}
sim_back = { version = "0.0.0", path = "../sim_back" }
mir_llvm = { version = "0.0.0", path = "../mir_llvm" }
llvm = { version = "0.0.0", path = "../llvm" }
target = { version = "0.0.0", path = "../target"}

typed-index-collections = "3"
ahash = "0.8"
indexmap = "2.0"
smol_str = {version = "0.3", default-features=false}
lasso = {version = "0.7", features = ["ahash"]}
salsa = "0.17.0-pre.2"
rayon-core = "1"
camino = "1.1.4"
log = "0.4.19"

[build-dependencies]

xshell = "0.2.7"
stdx = {version ="0.0.0", path ="../../lib/stdx"}
target = { version = "0.0.0", path = "../target" }

[dev-dependencies]

mir_interpret = {version = "0.0.0", path = "../mir_interpret" }
mini_harness = { version = "0.0.1", path = "../../lib/mini_harness" }

expect-test = "1.4"
float-cmp =  "0.9"

[[test]]
name = "data_tests"
harness = false
