//! Simulator backend

use stdx::{impl_debug_display, impl_idx_from};

use hir::{CompilationDB, ModuleInfo, Node};
use hir_lower::{FlowKind, HirInterner, ImplicitEquation};
use lasso::Rodeo;
use mir::Function;

pub mod dae;
pub mod init;
pub mod node_collapse;
pub mod util;

mod context;
mod noise;
mod topology;

use context::{Context, OptimizationStage};
use dae::DaeSystem;
use init::Initialization;
use node_collapse::NodeCollapse;
use topology::Topology;

pub(crate) const WITH_CONTRIBUTES: bool = true;
pub(crate) const WITHOUT_CONTRIBUTES: bool = false;

#[derive(PartialEq, Eq, Clone, Copy, Hash)]
pub enum SimUnknownKind {
    /// The simulation unknown corresponding to nodal potential (in KCL form)
    KirchhoffLaw(Node),
    /// The simulation unknown corresponding to the flow in a branch
    BranchFlow(FlowKind),
    /// The simulation unknown implicitly generated by simulator
    Implicit(ImplicitEquation),
}

impl_debug_display! {
    match SimUnknownKind{
        SimUnknownKind::KirchhoffLaw(node) => "{node:?}";
        SimUnknownKind::BranchFlow(flow) => "br[{flow:?}]";
        SimUnknownKind::Implicit(node) => "{node}";
    }
}

/// An unknown in the system of DAE equations
#[derive(PartialEq, Eq, PartialOrd, Ord, Clone, Copy, Hash)]
pub struct SimUnknown(u32);
impl_idx_from!(SimUnknown(u32));
impl_debug_display! {match SimUnknown{SimUnknown(id) => "sim_node{id}";}}

pub struct CompiledModule<'a> {
    pub info: &'a ModuleInfo,
    pub dae: DaeSystem,
    // op-independent part of MIR function and HIR interner with cache slots
    pub init: Initialization,
    // collapsed node pairs
    pub node_collapse: NodeCollapse,
    // all model parameter setup utility function
    pub model_param_setup: Function,
    pub model_param_intern: HirInterner,
    // op-dependent part of MIR function and HIR interner
    pub eval: Function,
    pub intern: HirInterner,
}

impl<'a> CompiledModule<'a> {
    pub fn new(
        db: &CompilationDB,
        info: &'a ModuleInfo,
        literals: &mut Rodeo,
    ) -> CompiledModule<'a> {
        let mut ctxt = Context::new(db, literals, info);

        // compute the output values (with contributions)
        ctxt.compute_outputs::<WITH_CONTRIBUTES>();

        // execute the initial optimization pass
        ctxt.compute_cfg();
        ctxt.optimize(OptimizationStage::Initial);
        debug_assert!(ctxt.func.validate());

        // topology and DAE setup needs information of op-dependent instructions
        ctxt.init_op_dependent_insts();

        // collects contributions and form model internal topology
        let topology = Topology::new(&mut ctxt);
        debug_assert!(ctxt.func.validate());

        // setup residual and Jacobians, auto-diff instructions/blocks are inserted
        let mut dae = DaeSystem::new(&mut ctxt, topology);
        debug_assert!(ctxt.func.validate());

        // execute post-derivative optimization
        ctxt.compute_cfg();
        let gvn = ctxt.optimize(OptimizationStage::PostDerivative);
        debug_assert!(ctxt.func.validate());

        // TODO(JW): It seems that this has barely no effect on MIR and DAE
        dae.sparsify(&mut ctxt);

        // After derivative insertion and post-derivative optimization, op-dependent
        // instruction set changes. Perform a full taint for function split.
        ctxt.refresh_op_dependent_insts();

        // Split the raw function and separate op-independent instructions into another
        // function
        let mut init = Initialization::new(&mut ctxt, &gvn);
        debug_assert!(init.func.validate());

        // node collapse should only depend on op-independent values
        let node_collapse = NodeCollapse::new(&init, &dae, &ctxt);

        // JW: It seems that final stage optimization was missing here.
        // I'm not sure if this is intended to increase compile speed.
        //
        // However, if this is turned on, OpenVAF panics when simplifying CFG.
        // I suppose this is because some part of the optimizations has already
        // been covered during initialization function building.
        //
        // ctxt.optimize(OptimizationStage::Final);
        debug_assert!(ctxt.func.validate());

        // insert instance parameter setup into op-independent(initialization) function
        // TODO: refactor param initialization to use tables
        let inst_params: Vec<_> = info
            .params
            .iter()
            .filter_map(|(param, info)| info.is_instance.then_some(*param))
            .collect();
        init.intern.insert_param_init(db, &mut init.func, literals, false, true, &inst_params);

        // create a utility function to set up all model parameters
        let mut model_param_setup = Function::default();
        let mut model_param_intern = HirInterner::default();
        let model_params: Vec<_> = info.params.keys().copied().collect();
        model_param_intern.insert_param_init(
            db,
            &mut model_param_setup,
            literals,
            false,
            true,
            &model_params,
        );

        // simplify the model parameter setup utility function (with phi merge)
        // Note that no DCE is performed.
        ctxt.cfg.compute(&model_param_setup);
        mir_opt::simplify_cfg(&mut model_param_setup, &mut ctxt.cfg);
        mir_opt::sparse_conditional_constant_propagation(&mut model_param_setup, &ctxt.cfg);
        mir_opt::simplify_cfg(&mut model_param_setup, &mut ctxt.cfg);

        CompiledModule {
            info,
            dae,
            init,
            node_collapse,
            model_param_setup,
            model_param_intern,
            eval: ctxt.func,
            intern: ctxt.intern,
        }
    }
}
