[package]
name = "hir_ty"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license="GPL-3.0"

[badges]
maintenance = { status = "actively-developed" }

[lib]
doctest = false

[dependencies]
stdx = {version = "0.0.0", path = "../../lib/stdx" }
arena = {version = "0.0.0", path = "../../lib/arena" }

basedb = {version = "0.0.0", path = "../basedb" }
syntax = {version = "0.0.0", path = "../syntax"}
hir_def = {version = "0.0.0", path = "../hir_def" }

ahash = "0.8"
typed-index-collections = "3.1"

salsa = "0.17.0-pre.2"