[package]
name = "hir_def"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[badges]
maintenance = { status = "actively-developed" }

[lib]
doctest = false

[dependencies]
stdx = { version = "0.0.0", path = "../../lib/stdx" }
arena = { version = "0.0.0", path = "../../lib/arena" }
syntax = { version = "0.0.0", path = "../syntax" }
basedb = { version = "0.0.0", path = "../basedb" }

typed-index-collections = "3"
ahash = "0.8"
indexmap = "2.0"
salsa = "0.17.0-pre.2"

[dev-dependencies]
mini_harness = { version = "0.0.1", path = "../../lib/mini_harness" }
expect-test = "1.4"
parking_lot = "0.12"

[[test]]
name = "data_tests"
harness = false
